// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPCaisseEnregistreuse.Data;

#nullable disable

namespace TPCaisseEnregistreuse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230510144633_migration2")]
    partial class migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPCaisseEnregistreuse.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Electromenager"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Epicerie sucrée"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Entretien de la maison"
                        });
                });

            modelBuilder.Entity("TPCaisseEnregistreuse.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 3,
                            Description = "Blanc à frange",
                            ImageURL = "https://m.media-amazon.com/images/I/41gXsVV+2aL._AC_SY355_.jpg",
                            Nom = "Balai",
                            Prix = 9.9900000000000002,
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            CategorieId = 2,
                            Description = "Blanc à la framboise",
                            Nom = "Tablette de chocolat",
                            Prix = 15.5,
                            Stock = 8
                        },
                        new
                        {
                            Id = 3,
                            CategorieId = 1,
                            Description = "Dolce Gusto",
                            Nom = "Cafetiere",
                            Prix = 100.0,
                            Stock = 5
                        },
                        new
                        {
                            Id = 4,
                            CategorieId = 1,
                            Description = "Dyson",
                            Nom = "Aspirateur",
                            Prix = 699.99000000000001,
                            Stock = 2
                        });
                });

            modelBuilder.Entity("TPCaisseEnregistreuse.Models.Produit", b =>
                {
                    b.HasOne("TPCaisseEnregistreuse.Models.Categorie", null)
                        .WithMany("ProduitList")
                        .HasForeignKey("CategorieId");
                });

            modelBuilder.Entity("TPCaisseEnregistreuse.Models.Categorie", b =>
                {
                    b.Navigation("ProduitList");
                });
#pragma warning restore 612, 618
        }
    }
}
